name: Sync From Remote Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  sync: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dev4dev/sync-from-remote-action@v1.0.2
        id: sync
        with:
          source: 'https://github.com/dev4dev/ParentTestSDK'
      - name: Print result
        run: |
          echo ${{ steps.sync.outputs.synced }}
      - name: Create Pull Request
        if: ${{ steps.sync.outputs.synced }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[auto update] Version: ${{ steps.sync.outputs.version }}"
          title: "[auto update] Version: ${{ steps.sync.outputs.version }}"
          branch: "version/${{ steps.sync.outputs.version }}"
          reviewers: dev4dev
