name: Sync From Remote Repo

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '* * * * *'

jobs:
  precheck:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get remote version
        run: |
          echo "REMOTE_VERSION=$(git ls-remote --tags --sort='-v:refname' https://github.com/dev4dev/ParentTestSDK | grep -P "refs/tags/v?\d+.\d+.\d+$" | head -n 1 | awk '{print $2}' | awk -F/ '{print $NF}')" >> $GITHUB_ENV
      
      - name: Get local version
        run: |
          echo "LOCAL_VERSION=$(git tag --sort=-v:refname | head -n 1)" >> $GITHUB_ENV
      
      - name: Compare versions
        run: |
          if [[ env.REMOTE_VERSION != env.LOCAL_VERSION ]]
          then
            echo "sync=1" >> $GITHUB_ENV
          else
            echo "sync=0" >> $GITHUB_ENV
          fi
  
  sync:
    if: env.sync == 1
    runs-on: ubuntu-latest

    steps:
      - name: Sync repos
        run: echo "Syncing..."

