name: Sync From Remote Repo

on:
  schedule:
    - 0 0 * * * SUN

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get remote version
        run: git ls-remote --tags --sort='-v:refname' https://github.com/dev4dev/ParentTestSDK | grep -E "refs/tags/v?\d+.\d+.\d+$" | head -n 1 | awk '{print $2}' | awk -F/ '{print $NF}' | echo
      
      - name: Compare versions
        run: echo " Comparing with the local version"
