name: Sync From Remote Repo

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '* * * * *'

jobs:
  sync: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dev4dev/sync-from-remote-action@v1.0.1
        id: sync
        with:
          source: 'https://github.com/dev4dev/ParentTestSDK'
          gitName: 'Alex A'
          gitEmail: 'test@x-code.name'
      - name: Print result
        run: |
          echo ${{ steps.sync.outputs.result }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[auto update] Version: ${{ steps.sync.outputs.result.version }}"
          title: "[auto update] Version: ${{ steps.sync.outputs.result.version }}"
