name: Sync From Remote Repo

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '* * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get remote version
        run: |
          echo ::set-env name=REMOTE_VERSION::$(git ls-remote --tags --sort='-v:refname' https://github.com/dev4dev/ParentTestSDK | grep -P "refs/tags/v?\d+.\d+.\d+$" | head -n 1 | awk '{print $2}' | awk -F/ '{print $NF}')
      
      - name: Get local version
        run: |
          echo ::set-env name=LOCAL_VERSION::$(git tag --sort=-v:refname | head -n 1)
      
      - name: Compare versions
        run: |
          echo $REMOTE_VERSION
          echo $LOCAL_VERSION

