name: Tag a new version

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  tagging:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        git log --format=oneline
